"""empty message

Revision ID: 4abbaebfdf6d
Revises: e969e48aa561
Create Date: 2024-10-29 02:42:26.233346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4abbaebfdf6d'
down_revision = 'e969e48aa561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_constraint('restaurant_category_id_fkey', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('restaurant_category_id_fkey', 'restaurant_category', ['category_id'], ['id'])

    # ### end Alembic commands ###
