"""empty message

Revision ID: b8496992d20e
Revises: aff1600048f8
Create Date: 2024-10-23 23:21:11.185892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8496992d20e'
down_revision = 'aff1600048f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint('client_last_name_key', type_='unique')
        batch_op.drop_constraint('client_name_key', type_='unique')
        batch_op.drop_constraint('client_phone_number_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_unique_constraint('client_phone_number_key', ['phone_number'])
        batch_op.create_unique_constraint('client_name_key', ['name'])
        batch_op.create_unique_constraint('client_last_name_key', ['last_name'])

    # ### end Alembic commands ###
